// ---------------------------------------------------------------------------
//! \package     CleaningUnit
//! \file        Version.h
//! \brief       Defines the version number (This file is generated by the build process)
//!
//! \copyright   Copyright (C) 2011-2012 BlueBotics SA
// ----------------------------------------------------------------------------

#ifndef _VERSION_H_
#define _VERSION_H_

#include "System.h"

#endif //_VERSION_H_
